server:
    port: 8766

spring:
    application:
        name: cyb-spring-cloud-config-server
        
    cloud:
        config:
            label: master
            server:
                git:
                    uri: file:///data/config
                    searchPaths:
                    username:
                    password:

eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka/