server:
    port: 8766

spring:
    application:
        name: cyb-spring-cloud-config-server
        
    cloud:
        config:
            label: master
            server:
                git:
                    uri: file:///E:/github/cyb-spring-cloud-demo
                    searchPaths: config
                    username:
                    password:
                    
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/