version: '3'
services:
  eureka-server:
    image: hustcyb/cyb-spring-cloud-eureka-server:1.0.0-SNAPSHOT
    expose:
      - 8761

  config-server:
    image: hustcyb/cyb-spring-cloud-config-server:1.0.0-SNAPSHOT
    volumes:
      - ./config-server/application.yml:/data/cyb-spring-cloud-config-server/config/application.yml:ro
      - ./config-server/config:/data/config
    expose:
      - 8766
    links:
      - eureka-server

  config-client:
    image: hustcyb/cyb-spring-cloud-config-client:1.0.0-SNAPSHOT
    volumes:
      - ./config-client/bootstrap.yml:/data/cyb-spring-cloud-config-client/config/bootstrap.yml:ro
    ports:
      - "8767:8767"
    links:
      - eureka-server
      - config-server