version: '3'
services:
  eureka-server:
    image: hustcyb/cyb-spring-cloud-eureka-server:1.0.0-SNAPSHOT
    expose:
      - 8761

  eureka-client:
    image: hustcyb/cyb-spring-cloud-eureka-client:1.0.0-SNAPSHOT
    volumes:
      - ./eureka-client/application.yml:/data/cyb-spring-cloud-eureka-client/config/application.yml:ro
    expose:
      - 8762
    links:
      - eureka-server

  ribbon-service:
    image: hustcyb/cyb-spring-cloud-ribbon-hystrix-service:1.0.0-SNAPSHOT
    volumes:
      - ./ribbon-service/application.yml:/data/cyb-spring-cloud-ribbon-hystrix-service/config/application.yml:ro
    expose:
      - 8763
    links:
      - eureka-server
      - eureka-client

  feign-service:
    image: hustcyb/cyb-spring-cloud-feign-hystrix-service:1.0.0-SNAPSHOT
    volumes:
      - ./feign-service/application.yml:/data/cyb-spring-cloud-feign-hystrix-service/config/application.yml:ro
    expose:
      - 8764
    links:
      - eureka-server
      - eureka-client

  zuul-proxy:
    image: hustcyb/cyb-spring-cloud-zuul-proxy:1.0.0-SNAPSHOT
    volumes:
      - ./zuul-proxy/application.yml:/data/cyb-spring-cloud-zuul-proxy/config/application.yml:ro
    ports:
      - "8765:8765"
    links:
      - eureka-server
      - eureka-client
      - ribbon-service
      - feign-service