eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka/

server:
    port: 8764

spring:
    application:
        name: cyb-spring-cloud-feign-service
        
feign:
    client:
        hello: cyb-spring-cloud-eureka-client